# Generated by Django 2.1.7 on 2019-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=250)),
                ('channel_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
