# Generated by Django 2.1.7 on 2019-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=250)),
                ('channel_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
