# Generated by Django 2.1.7 on 2019-04-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_channel_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Channel')),
            ],
        ),
    ]
