# Generated by Django 2.1.7 on 2019-04-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20190409_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=10000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Channel')),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='album',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
