# Generated by Django 2.1.7 on 2019-04-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20190415_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='users',
        ),
    ]
