# Generated by Django 2.1.7 on 2019-04-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_channel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='src',
        ),
        migrations.RemoveField(
            model_name='fchannel',
            name='src',
        ),
        migrations.AddField(
            model_name='fchannel',
            name='channel_logo',
            field=models.FileField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chan',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.FChannel'),
        ),
    ]
