# Generated by Django 2.1.7 on 2019-04-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20190416_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='dele',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='News.FChannel'),
        ),
    ]
