# Generated by Django 2.1.7 on 2019-04-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_remove_channel_dele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_logo',
        ),
    ]
