# Generated by Django 2.1.7 on 2019-04-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_remove_channel_channel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channels',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='News.FChannel'),
        ),
    ]
