# Generated by Django 2.1.7 on 2019-04-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_channel_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channels',
        ),
    ]
