# Generated by Django 2.1.7 on 2019-04-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0017_remove_channel_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='album',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='News.FChannel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_logo',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
