# Generated by Django 2.1.7 on 2019-04-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0018_auto_20190417_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chan',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Channel'),
        ),
    ]
