# Generated by Django 2.1.7 on 2019-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0019_auto_20190417_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chan',
            old_name='album',
            new_name='albums',
        ),
    ]
