# Generated by Django 2.1.7 on 2019-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0021_auto_20190417_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chan',
            name='album',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_call',
            field=models.CharField(default=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='fchannel',
            name='channel_call',
            field=models.CharField(default=True, max_length=10000),
        ),
        migrations.DeleteModel(
            name='Chan',
        ),
    ]
